### ISSUE TITLE
Date des articles de revue

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#1]
Corriger l'affichage des dates pour ne montrer que **yyyy** à la place de **dd-mm-yyyy** lorsqu'il s'agit d'articles de revues en ligne (pas lorsqu'il s'agit de billets/web/newspapers/etc.).

**Comment by nchachereau** [comment]
Faut-il que cela s'applique à tous les documents de type [Article de revue], ou seulement à ceux qui ont URL ou DOI («articles de revues en ligne»)?

Ma préférence va à la première solution. Qu'en penses-tu?

**Comment by grandjeanmartin** [comment]
Idem, tout article de ce type, sans limitation.
