### ISSUE TITLE
Affichage du champ "Type de site web"

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#11]
L'exemple du communiqué de presse d'economiesuisse #5 montre que le champ "Type de site web" s'affiche. Ca pourrait être intéressant (dans ce cas particulier, ça ajoute une bonne information à la référence), mais est-ce qu'il ne risque pas d'y avoir tout et n'importe quoi dans ce champ ? À mon sens, il faudrait l'enlever, pour éviter d'avoir des références qui contiennent des éléments "méta" ne faisant pas partie de la source elle-même.

**Comment by nchachereau** [comment]
C'est fait (même si le risque était assez faible: il y a peu de captures de sites web qui rajoutent cette information dans Zotero). D'ailleurs, l'exemple «communiqué de presse» a été rajouté à la main.
