### ISSUE TITLE
Affichage du volume+pages dans une note

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#15]
Petit détail rencontré lors de la mise au point du guide : lorsqu'un ouvrage a plusieurs volumes, il est difficile d'insérer une référence précise en note parce qu'il n'y a qu'un champ "pages" dans le menu d'importation. Si on ne met que le numéro de la page, le lecteur ne sait pas dans quel vol. chercher, et si on met "vol. 1, p. 14", Zotero traduit en "p. vol. 1, 14".

**Comment by nchachereau** [comment]
Je ne crois pas pouvoir intervenir au niveau du style sur ce point. Par contre, il suffit d'indiquer «volume» à la place de «page» lors de l'importation:

![exemple](https://user-images.githubusercontent.com/904912/50080269-fde38700-01eb-11e9-8eb5-a76e79a1d7fe.png)

Ou alors, comme on en avait discuté, conserver des références séparées pour les différents volumes (ce qui a du sens, par exemple, lorsque les volumes ont des dates et des titres différents).

**Comment by grandjeanmartin** [comment]
Ah je n'avais pas cherché jusque là, c'est évidemment la solution. Je ne crois pas que je vais l'intégrer dans le guide, c'est vraiment une fonctionnalité avancée, non ?

**Comment by nchachereau** [comment]
C'est pas une fonctionnalité très avancée, à mon avis, mais ce n'est pas très utile pour le Guide, je suis d'accord. À intégrer plutôt dans un éventuel tutoriel Zotero.
