### ISSUE TITLE
Affichage des [s.d.]

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#16]
En l'état, si une référence n'a pas de date, le style ajoute "s. d." lorsque l'on insère la ref. Or, notre style dit qu'il faut mettre "[s.d.]" (avec crochets carrés et sans espace). Je pense qu'on devrait rétablir ça à l'occasion (par contre, je ne sais pas si c'est moi qui ai introduit l'absence d'espace dans le guide ou si c'était déjà le cas avant).

**Comment by nchachereau** [comment]
OK je m'en occupe assez vite, j'espère demain.

> par contre, je ne sais pas si c'est moi qui ai introduit l'absence d'espace dans le guide ou si c'était déjà le cas avant

Déjà le cas avant, d'après la copie du guide bibliographique dont je dispose. On fait comme ça? (Personnellement je préfère avec espace, mais bon c'est vraiment du détail)

**Comment by grandjeanmartin** [comment]
Ok, on fait comme le guide alors. Et à l'occasion on peut lancer un débat... (mais dans l'immédiat, c'est plus simple de ne pas changer le guide)
