### ISSUE TITLE
Suffixe "p." pour les pages manquant (pandoc, citeproc et .bib)

### ISSUE THREAD

**Issue by Aubrays** [LausanneCitationStyle/Lausanne#19]
Bonjour,

Je teste actuellement un nouveau processus de rédaction, fortement inspiré de ce que propose l'outil [Academic Pandoc template](https://github.com/maehr/academic-pandoc-template). Et j'ai découvert que dans le PDF obtenu, il manque le "p." pour les pages des livres avec le style Lausanne (mais pas dans [ce style](https://www.zotero.org/styles/histoire-at-politique?source=1) choisi au hasard).

## Mon processus

Depuis Zotero, j'exporte un fichier .bib avec le plugin [Better BibTeX](https://retorque.re/zotero-better-bibtex/) au format BibLaTeX.

Après avoir rédigé mon texte en Markdown, j'utilise Pandoc couplé à citeproc pour générer un pdf avec XeLaTeX. 

### Exemple minimal
Extrait de mon fichier .bib après export :
```bibtex
@book{biemontRythmesTempsAstronomie2000,
  title = {Rythmes du temps. Astronomie et calendriers},
  shorttitle = {Rythmes du temps},
  author = {Bi\'emont, Emile},
  date = {2000},
  publisher = {{De Boeck}},
  location = {{Paris, Bruxelles}},
  isbn = {978-2-8041-3287-3},
  langid = {french},
  pagetotal = {393}
}
```

Mon document Markdown :
```md
---
lang: fr-CH
title: "Exemple minimal pour le nombre de pages d'un livre"
author: "John Doe"
date: "30.01.2021"

csl: https://www.zotero.org/styles/universite-de-lausanne-histoire
bibliography: maBilbliographie.bib
nocite: '@*' #pour citer tout le contenu du fichier .bib en fin de document
---
Lorem ipsum
```
La ligne de commande minimale pour la génération du PDF :
```bash
pandoc --citeproc --pdf-engine=xelatex --standalone monDocument.md -o monDocument.pdf
```
Le rendu final de la citation est la suivante :
```
Biémont Emile, Rythmes du temps. Astronomie et calendriers, Paris, Bruxelles : De Boeck,
2000, 393.
```
Auriez-vous une solution ou une piste de recherche dans le fichier CSL pour résoudre le problème ?

Merci d'avance pour votre aide !

**Comment by nchachereau** [comment]
Bonjour,

Content de vous voir par ici!

Merci d'avoir signalé ce problème. Cela devrait être corrigé, pourriez-vous tester en installant manuellement le fichier CSL de ce répertoire? Si cela fonctionne pour vous aussi je demanderai que cette correction soit incluse dans la version des répertoires officiels des styles CSL.

(Je vous passe les détails, mais l'autre style que vous avez trouvé ne faisait pas cela très proprement. J'espère que cette solution sera meilleure.)

**Comment by Aubrays** [comment]
Content de pouvoir utiliser ce style tout prêt et bien pratique !
Je confirme que la modification fonctionne. Merci beaucoup !
