### ISSUE TITLE
Métadonnées du style

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#2]
Modifier les métadonnées, avec un nouveau titre et les nouveaux auteurs. Créditer le style Infoclio et ses auteurs.

**Comment by nchachereau** [comment]
- [x] choisir un titre
- [x] chercher dans la spéc CSL comment créditer un style précédent
- [x] disposer d'une URL stable vers la documentation en ligne
- [x] ajouter ces éléments dans le style

**Comment by grandjeanmartin** [comment]
Pour la 1) -> #3 
Pour la 3) ce que je ferais, c'est créer une organisation Github et copier ce projet dedans pour lui donner un caractère définitif (ou dire que c'est celui-là? mais l'organisation permet d'être indépendante de ton compte perso) et l'archiver avec Zenodo. Ca me semble beaucoup plus sûr que de faire une page sur le site de la section, dont les URL pourraient très bien changer sans crier gare.

**Comment by grandjeanmartin** [comment]
Ah, j'ajoute, est-ce qu'il y a un moyen de noter la version dans le style ? Ca permettrait de vérifier, lors d'une mise à jour, lequel est installé.

- [ ] Ajouter v.1 dans les méta

**Comment by nchachereau** [comment]
Il n'y a pas à proprement parler d'élément pour noter la version. CSL s'appuie sur un timestamp dans un champ `<updated>`: Zotero compare la date de mise à jour du style installé localement avec celui des dépôts, et télécharge l'éventuelle nouvelle version (cf. la colonne «Mis à jour» dans l'onglet «Citer» des préférences).

Ce fonctionnement automatique me semble suffisant. Si besoin est, on peut toujours comparer le champ `<updated>` d'un style local (p. ex. d'un utilisateur demandant de l'aide) avec celui du commit correspondant au tag d'une certaine version.

J'ai configuré mon éditeur de texte pour que le champ `<updated>` soit mis à jour automatiquement lorsque je sauvegarde le fichier, donc les commit seront bons de ce point de vue.
