### ISSUE TITLE
Lieu(x) d'édition

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#4]
Dans notre feuille de route, on indique "lieux d'éditions : d'accord de ne mettre que le premier?" mais si je ne me trompe pas, le style les affiche tous, non ? (en tout cas l'exemple de notre comparateur, "KENNEY", les affiche les 2)
Du coup, on laisse l'affichage de lieux multiples ? (n'afficher que le premier ne serait ainsi qu'une recommandation lors de l'entrée manuelle des métadonnées)

**Comment by nchachereau** [comment]
Le style CSL reçoit simplement le contenu des champs `Lieu` et `Éditeur`, tels quels, et ne peut pas distinguer s'il y a plusieurs lieux ou éditeurs. La mention de la feuille de route concernait une éventuelle indication à donner dans le guide, mais qui n'est pas liée au style Zotero.

Au vu de la consultation, je pense qu'on peut laisser cette recommandation de côté.

Par contre le style ne saura pas faire ce que le guide de la section préconisait (Genève : Droz, Louvain : Presses universitaires de Louvain − cf. l'exemple Gilmont), mais affichera le champ `Lieu` suivi du champ `Éditeur` (autrement dit quelque chose comme «Genève ; Louvain : Droz ; Presses universitaires de Louvain»).

Donc peut-être plutôt intégrer dans la documentation une recommandation de corriger manuellement les références sur ce point ?
