### ISSUE TITLE
Vérifier les références d'autres types de documents

### ISSUE THREAD

**Issue by nchachereau** [LausanneCitationStyle/Lausanne#5]
Ci-dessous, voici ce que donnent à l'heure actuelle les références (en bibliographie, pas en note) pour certains types de documents non mentionnés dans le guide bibliographique d'origine. Il faudrait les vérifier, et créer des issues pour les références inadéquates.

### Thèses
> ESPOSITO, Piergiuseppe, _« Health & pleasure »: le tourisme médico-sanitaire dans l’Arc lémanique et le Chablais vaudois : de la consommation de soins à l’innovation de produit (1850-1914)_, Thèse de doctorat, Lausanne : Université de Lausanne, 2017.

### Articles d'encyclopédie
> SALATHE, André, « Bernina », in _Dictionnaire historique de la Suisse_, 27.06.2002. En ligne: http://www.hls-dhs-dss.ch/textes/f/F41930.php.

### Littérature grise / rapports
(ici, working paper)
> MACLEOD, Christine et NUVOLARI, Alessandro, « Inventive Activities, Patents and Early Industrialization. A Synthesis of Research Issues », DRUID Working Paper, DRUID, Copenhagen Business School, Department of Industrial Economics and Strategy/Aalborg University, Department of Business Studies, 2006. En ligne: http://ideas.repec.org/p/aal/abbswp/06-28.html.

### Sources d'archives
> Rapport concernant les collections d’exposés d’invention cédées gratuitement, 19.02.1913, Archives fédérales, Berne, E 4380 (B), 1992-255 vol. 27, dossier «Verminderung der öffentlichen Auflagestellen 1913».

### Articles de journal
> « Faits divers », _Journal de Genève_, Genève, 17.05.1855, p. 3.

> Ravussin, Frédéric, « Un des pères des platines Thorens s’en est allé », _24Heures_, 06.11.2018. En ligne: https://www.24heures.ch/vaud-regions/nord-vaudois-broye/peres-platines-thorens-s/story/30729668.

### Site web et articles en ligne
> « Propriété intellectuelle : une vue d’ensemble grâce à la 11e édition de l’ICC IP Roadmap », communiqué de presse, _economiesuisse_, 24.01.2012, http://www.economiesuisse.ch/fr/themen/wb/swissness/pages/_detail.aspx?artID=Neue-ICC-Roadmap-Immaterialgueterrecht-schafft--Ueberblick, consulté le 26.01.2012.

### Billets de blog
> KÖNIG, Mareike, « Guck mal, wer da bloggt! Neue Blogs bei de.hypotheses.org », _Redaktionsblog_, 26.04.2012, http://redaktionsblog.hypotheses.org/485, consulté le 12.01.2015.

**Comment by grandjeanmartin** [comment]
Du coup, on a tout ?

**Comment by nchachereau** [comment]
Ça serait bien de tester les modifications.

Par ailleurs, en regardant la liste de références, il me reste une question: est-ce que les dates au format DD.MM.YYYY nous conviennent? On pourrait aussi envisager D.M.YYYY (26.4.2012) ou même le mois en toutes lettres 26 avril 2012.

On pourra certainement soumettre le style au dépôt officiel cette semaine.
