### ISSUE TITLE
Corriger références d'archives

### ISSUE THREAD

**Issue by nchachereau** [LausanneCitationStyle/Lausanne#6]
À l'heure actuelle, les documents d'archives sont cités avec le titre (la description) du document au début (cf. #5).

Or, dans la pratique de la section d'histoire, un document d'archives est plutôt cité en indiquant l'institution archivistique, le fonds et la cote en début de référence, et le titre / description du document à la fin.

**Comment by grandjeanmartin** [comment]
Oui, le nom de l'institution en premier. Par ailleurs, le titre du document lui-même en italique ?

**Comment by nchachereau** [comment]
Le problème c'est qu'on a souvent pas de titre, mais simplement une caractérisation du document (p. ex. «rapport dactylographié»), pour lequel les italiques ne conviennent pas...

**Comment by nchachereau** [comment]
À noter: dans le style infoclio, l'information sur les archives est affichée lorsqu'elle était présente dans la bibliothèque Zotero, quel que soit le type du document. Cela permet par exemple d'afficher la collection pour une œuvre d'art, mais pose le problème d'afficher le contenu du champ «Archive» lorsqu'il n'est pas pertinent (dans ma bibliothèque, j'ai certaines références avec l'«archive» «Cambridge Core»…).

Pour rester dans la philosophie de ce style («il vaut mieux en montrer pas assez que trop»), l'affichage de la localisation en archives ne se fait que pour les types Lettre, Courriel, Message instantané (que le style voit tous trois comme `personal_communication`) et Manuscrit.
