### ISSUE TITLE
Généraliser l'indication du nombre de pages

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#7]
Actuellement (voir #5), il me semble qu'il manque aux références des thèses de doctorat le **nombre de pages**, qui est affiché pour tous les autres documents de type "ouvrage" (mais en est-ce vraiment un ?).

**Comment by nchachereau** [comment]
OK pour moi. La logique qui s'applique aux ouvrages (indiquer la longueur) s'applique aussi aux thèses de doctorat et à mon avis aussi à la littérature grise.

**Comment by nchachereau** [comment]
Après vérification, le style affiche le nombre de pages s'il est présent dans la notice Zotero, sans différencier selon les types. Ça marche donc déjà.

**Comment by nchachereau** [comment]
Ah, et en fait il n'y a pas de champ «nombre de pages» pour les documents de type «Rapport».
