### ISSUE TITLE
L'indication des URL n'est pas uniforme

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/Lausanne#8]
Les exemples de formats supplémentaires de #5 montrent qu'on est pas systématique sur l'intégration des URL. Parfois introduites par "En ligne", parfois pas. Quelle est la logique ? Et ne faudrait-il pas généraliser (soit en mettant "en ligne" partout, soit en l'enlevant partout) ?

**Comment by nchachereau** [comment]
Comme discuté rapidement, la logique était d'indiquer le statut particulier des URL pour les documents disposant aussi d'une version «hors ligne». La distinction tend à perdre de sa pertinence, et Zotero ne permet pas tout à fait de la faire de toute façon. Donc OK pour supprimer l'indication «En ligne».

Virgule ou point pour séparer l'URL du reste de la référence?

**Comment by grandjeanmartin** [comment]
Je dirais virgule.
